version: '3'

services:
  # Application
  asiance:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: asiance_app
    environment:
      SERVICE_NAME: asiance
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - asiance-network

  # Web-server - Nginx
  webserver:
    image: nginx:alpine
    container_name: asiance_webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - asiance-network

  # Database
  db:
    image: mysql:5.7.22
    container_name: asiance_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: asiance
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - asiance-network

# Networks
networks:
  asiance-network:
    driver: bridge

# Volumes
volumes:
  dbdata:
    driver: local